[tool.poetry]
name = "flatpak_builder_lint"
version = "0.0.1"
description = "A linter for flatpak-builder manifests"
authors = ["Bartłomiej Piotrowski <b@bpiotrowski.pl>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pyflakes = "^2.5.0"
mypy = "^0.971"
pylint = "^2.14.5"
pre-commit = "^2.20.0"
isort = "^5.10.1"
black = "^22.6.0"

[tool.poetry.scripts]
flatpak-builder-lint = "flatpak_builder_lint.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_unused_ignores = true
show_error_codes = true
warn_return_any = true
