name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache flatpak build
        uses: actions/cache@v3
        with:
          path: docker/.flatpak-builder
          key: fb-${{ matrix.platform }}-${{ hashFiles('poetry.lock', 'docker') }}

      - name: Build flatpak-builder-lint
        run: |
          cd docker
          bash -x ./build.sh ${{ matrix.platform }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: docker
          file: docker/Dockerfile
          platforms: linux/${{ matrix.platform }}
          load: true
          tags: |
            ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-${{ matrix.platform }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git
            org.opencontainers.image.url=https://github.com/${{ github.repository }}

  docker-manifest:
    runs-on: ubuntu-latest
    needs:
      - docker
    permissions:
      packages: write
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          docker manifest create \
            ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }} \
            --amend ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-amd64 \
            --amend ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-arm64
            --annotation "index:org.opencontainers.image.revision=${{ github.sha }}" \
            --annotation "index:org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git" \
            --annotation "index:org.opencontainers.image.url=https://github.com/${{ github.repository }}"

          docker manifest push ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}

      - name: Tag and push latest
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker tag ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }} ghcr.io/flathub-infra/flatpak-builder-lint:latest
          docker push ghcr.io/flathub-infra/flatpak-builder-lint:latest

      - name: Login to ghcr.io using Flathub credentials
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.FLATHUB_ORG_USER }}
          password: ${{ secrets.FLATHUB_ORG_TOKEN }}

      - name: Push image to the old location
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker tag ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }} ghcr.io/flathub/flatpak-builder-lint:${{ github.sha }}
          docker push ghcr.io/flathub/flatpak-builder-lint:${{ github.sha }}

          docker tag ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }} ghcr.io/flathub/flatpak-builder-lint:latest
          docker push ghcr.io/flathub/flatpak-builder-lint:latest
